image: alpine/edge
oauth: pages.sr.ht/PAGES:RW
packages:
  - hut
  - zine
environment:
  site: medzernik.dev
tasks:
  - compile: |
      cd $site
      zine --version
      zine release
  - package: |
      cd $site
      tar -C public -cvz . > site.tar.gz
  - upload: |
      cd $site
      hut pages publish -d $site site.tar.gz
