image: alpine/edge
oauth: pages.sr.ht/PAGES:RW
packages:
  - hut
  - curl
  - tar
environment:
  site: medzernik.dev
tasks:
  - zine: |
      curl https://github.com/kristoff-it/zine/releases/download/v0.13.0/x86_64-linux-musl.tar.xz -O -L
      tar -xvf x86_64-linux-musl.tar.xz
      pwd
  - version: |
      zine --version
  - compile: |
      cd $site
      zine release
  - package: |
      cd $site
      tar -C public -cvz . > site.tar.gz
  - upload: |
      cd $site
      hut pages publish -d $site site.tar.gz
